import org.example.User;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


// class generated by Chatgpt
class UserTest {

    @Test
    void testAdminConstructor() {
        User adminUser = new User("John", "Doe", "adminUser", "password123", "adminPass");
        assertEquals("John", adminUser.getFirstName());
        assertEquals("Doe", adminUser.getLastName());
        assertEquals("adminUser", adminUser.getUsername());
        assertEquals("password123", adminUser.getPassword());
        assertEquals("admin", adminUser.getAdminPassword()); // Should always be "admin"
    }

    @Test
    void testRegularUserConstructor() {
        User regularUser = new User("Jane", "Doe", "user123", "pass456");
        assertEquals("Jane", regularUser.getFirstName());
        assertEquals("Doe", regularUser.getLastName());
        assertEquals("user123", regularUser.getUsername());
        assertEquals("pass456", regularUser.getPassword());
        assertEquals("usr", regularUser.getAdminPassword()); // Should always be "usr"
    }

    @Test
    void testSettersAndGetters() {
        User user = new User("John", "Doe", "johndoe", "secret");

        user.setFirstName("Alice");
        user.setLastName("Smith");
        user.setUsername("alicesmith");
        user.setPassword("newpass");
        user.setAdminPassword("superadmin");

        assertEquals("Alice", user.getFirstName());
        assertEquals("Smith", user.getLastName());
        assertEquals("alicesmith", user.getUsername());
        assertEquals("newpass", user.getPassword());
        assertEquals("superadmin", user.getAdminPassword());
    }
}
